[package]
name = "batan"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.59"
bincode = "1.3.3"
futures = "0.3.25"
lapin = "2.1.1"
once_cell = "1.16.0"
serde = { version = "1.0.148", features = ["derive"] }
thiserror = "1.0.37"
tracing = "0.1.37"
