[package]
name = "monaxia"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sea-query = { workspace = true }
sqlx = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

axum = "0.6.18"
axum-extra = "0.7.4"
clap = { version = "4.3.11", features = ["derive"] }
toml = "0.7.6"
