[package]
name = "monaxia-data"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

toml = "0.7.6"

monaxia-db = { workspace = true }
