[server]
bind = "0.0.0.0:3000"
schema = "https"
domain = "your-domain.tld"
# port = 443

[database]
url = "postgres://monaxia:einsamkeit@postgres:5432/monaxia"

[user]
registration = "closed"
username_max_length = 32
banned_usernames = []
