[server]
bind = "0.0.0.0:3000"
schema = "http"
domain = "localhost"
port = 3000

[database]
url = "postgres://localhost:5432/monaxia"

[user]
registration = "closed"
username_max_length = 32
banned_usernames = []
