[workspace]
resolver = "2"
members = ["batan", "monaxia", "xtask"]

[workspace.dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.11", features = ["derive"] }
serde = { version = "1.0.171", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = { version = "2.4.0", features = ["serde"] }
